### ISSUE TITLE
ModuleDisabled check is broken (always fails)

### ISSUE THREAD

**Issue by briantully** [fiasco/drutiny-plugin-drupal-7#9]
we are seeing the same issue with D7 ModuleDisabled audit as previously occurred in the plugin-drupal-8 ModuleDisabled audit, whereby a module can either be Not Installed or Disabled. The current audit only checks for "not installed" and will fail if module status is "disabled".

We should port the change from plugin-drupal-8 over to plugin-drupal-7

**Comment by fiasco** [comment]
Agreed - this makes sense.
